name: GKE Deployment

on:
  push:
    branches: [main]

env:
  PROJECT_ID: my-app-458011
  CLUSTER_NAME: app-cluster-01
  ZONE: us-central1-a # or REGION for regional clusters
  VPC_NETWORK: main-vpc
  SUBNET: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate to GCP
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCPQlt++vgTz/CH\nvXGgHnYcJ/MtSqL1eLUha1twhT9x7Bo6UN7Te/emBOtboyAr+1V6NEXsrhNzzPI2\njFUKRxXs/F2D0hni7wtLvsAA2KzP8rBArbaSo/tJ5JpkiijryN4/S+uzuvqTYGm6\nR7AgezVtaMw7PPBA7SS+hxQqehro2fa6SIiVghe+0WULPZ8zRxqDnHND7w0JhNHc\n86hySIJsB2xATmZXIgEx3zuVaz7HII+GugXtuLtdE7dVp5lPVL3oq2wbXJT+e4Q5\npRqkEPcBSD4dEzumvrhQcck1nCwrp43Ic/WH5MDdksw/K5xug/co5+7SbN1VAQYq\nPQDFl+WxAgMBAAECggEAAeTMVYBhznk9jRMkW7aAtIc+qrGa4oh8SdB5KU1Jn8A8\nPzBvJvfeN96cHIj/1YpWq0KM+L+lrYPfC843wuavqS3+L84+M1waQnUSEAYikAPS\n7/fxOuevXF8I6h1SxH3SRPSZorWXtw0GOMUr1IdsbGF/RE/ePoLOrTTB6nx/ZeaT\n+8YshmlQ8XctUHVPkean/bfjGwzsOKi6wj8GCrIkKKEKZ7RRqQu8zub4CA7GLCU/\nK/9LkwRisrVGXETUeG9mmsT1TnUAJW+h0nW+eZbdS1/2FIWEOFw0Vev2EovG4LEN\neeKSesNLbL27iW1xbh6aWkXfWSLcOKyxkDz+xdlO5QKBgQDCFea7tR+WLuigkBA7\nf2r0wKHsRcOBWd0qy7u4FJOhB7++wpb3075K8r0v/0h3quznUWFlEFQ8ZQpd4jDz\nsn7Itc0lByxBzQohSTyFU9WjNn7QfG2WD8l7gjDuoOjXjjQ7ZHALky14jPN48OqP\n4DVHvdaeeoi3jSyfge72YsA74wKBgQC89bIvmNKXl46CM0j2Ape46FiMO1Rw61wt\nVEMuZ7MNSrWxA49ugQGmTDNml5KBsRuHiHCwuruOHDGdjOsmeFSdx4jbMqIDFSP8\n9wmmKCQEbezA6fOJpvyEkxDi5uTAIvASL/5KSbBuOgT+QN02cuosvwVoq43a3Iop\nHY0TsO20WwKBgQCxLzljp+jcPJrW6m5HQv2rz6iDgPUIw7dreG85kF9uJRrh1dfp\nC/+vgIdCqDXKOdrpGpxlnVCpijy6lOLHt+6S4ZYU9cVrlPpohOmhdnWU+Q0w3EdX\nNbZk8OgnEfM/xmzcw8aeapCae2NSx+37x14czqx+JbNmjpVsUTyM5n5ErQKBgF3x\n7Zgaa8EweYqkAsdEvLgS1EtMCAxoB5kFxqzgo7WdCj4qnfn7q51JT1jXTOCr9Brr\nK9PB0xOxUr2Y3SRwOOmE1bbdMo1DynOvQp3YYSfOmyHCbvFmEy+6im+1Cc+4zxDL\nyaqXfl8e+3KJPzId6e07P24ttMY2VX5hkc1Tbqr3AoGBAJPYCrgoII/kjHGNbMmx\n7Rl2nuMdNUV/BxEtA6OkkGYn6cHSdn/M21Vy9YHaYOT0faGEn487RgQw20VU+zIQ\n/EAlMzf77aBtTunY+S0ZgYYAGGkbfbUfzN/GInGnTuEkHEC2vkyQwttJ75peIZiv\nQgglDtS5dLQt5r2yiolKO8yQ\n-----END PRIVATE KEY-----\n"

      # Set up gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Connect to cluster in your VPC
      - name: Configure kubectl
        run: |-
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $ZONE \
            --project $PROJECT_ID \
            --internal-ip  # Uses VPC internal networking

      # Build and push to GCR (using your VPC network)
      - name: Build and Push
        run: |-
          docker build --network=cloudbuild \
            -t gcr.io/$PROJECT_ID/flask-app:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/flask-app:${{ github.sha }}

      # Deploy with VPC-native networking
      - name: Deploy
        run: |-
          kubectl apply -f k8s/
          kubectl rollout status deployment/flask-app
          kubectl get svc -o wide
